#!/usr/bin/env bash
#Bash script that displays all active IPv4 IPs on the machine it’s executed on
#ip -4 addr show | awk '/inet / {print $2}' | cut -d'/' -f1
ifconfig | grep 'inet ' | awk '{print $2}'
